package valvebilling

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The vectors are generated by the monorepo from its REAL hashApiKey — not
// recomputed from a second HMAC — so they are authoritative rather than
// self-confirming. They are copied into this repo rather than read across the
// two working trees, because CI here cannot see the monorepo. Regenerate them
// there and copy them again if the construction ever changes.
//
// Every value in the file is synthetic. It carries no production pepper and no
// production API key, which is why it is safe to commit.
const hashVectorFile = "testdata/hash-api-key-vectors.json"

type hashVector struct {
	Why             string `json:"why"`
	Pepper          string `json:"pepper"`
	APIKey          string `json:"apiKey"`
	APIKeyUTF8Bytes int    `json:"apiKeyUtf8Bytes"`
	Expected        string `json:"expected"`
}

type hashVectorFileShape struct {
	Note         string         `json:"note"`
	Construction map[string]any `json:"construction"`
	Vectors      []hashVector   `json:"vectors"`
}

func loadHashVectors(t *testing.T) hashVectorFileShape {
	t.Helper()
	raw, err := os.ReadFile(hashVectorFile)
	require.NoError(t, err, "the shared vectors must be present; this test is the only proof the two languages agree")
	var f hashVectorFileShape
	require.NoError(t, json.Unmarshal(raw, &f))
	require.NotEmpty(t, f.Vectors, "an empty vector file would make this test pass by doing nothing")
	return f
}

// This is the conformance test the brief requires. The api service writes the
// Redis buckets this module reads, and it addresses them by this digest — so a
// disagreement of one character means every lookup misses and the customer
// looks unmetered rather than misconfigured. Nothing goes red.
func TestHashAPIKey_AgreesWithTheTypeScriptImplementation(t *testing.T) {
	f := loadHashVectors(t)

	for _, v := range f.Vectors {
		t.Run(v.Why, func(t *testing.T) {
			got, err := HashAPIKey(v.Pepper, v.APIKey)
			require.NoError(t, err)
			assert.Equal(t, v.Expected, got,
				"digest disagrees with TypeScript for vector %q", v.Why)
			assert.Len(t, got, APIKeyHashLength,
				"a digest of the wrong length addresses a different key namespace")
		})
	}
}

// The UTF-8 vectors only pin the encoding if the bytes they claim are the
// bytes Go sees. Without this, an encoding disagreement could hide inside a
// vector whose expected digest was generated from the same wrong assumption.
func TestHashAPIKey_VectorsAgreeOnUTF8Lengths(t *testing.T) {
	f := loadHashVectors(t)
	nonASCII := 0
	for _, v := range f.Vectors {
		assert.Equal(t, v.APIKeyUTF8Bytes, len([]byte(v.APIKey)),
			"vector %q disagrees with Go on how many bytes its key is", v.Why)
		for _, r := range v.APIKey {
			if r > 127 {
				nonASCII++
				break
			}
		}
	}
	assert.GreaterOrEqual(t, nonASCII, 1,
		"at least one vector must carry a non-ASCII key, or the UTF-8 encoding is not pinned at all")
}

// The pepper must be the HMAC key, not something folded into the message. The
// file carries two vectors with the SAME key under DIFFERENT peppers for
// exactly this; assert the property rather than trusting the label.
func TestHashAPIKey_ThePepperChangesTheDigest(t *testing.T) {
	f := loadHashVectors(t)

	byKey := map[string][]hashVector{}
	for _, v := range f.Vectors {
		byKey[v.APIKey] = append(byKey[v.APIKey], v)
	}

	compared := 0
	for key, group := range byKey {
		for i := 1; i < len(group); i++ {
			if group[i].Pepper == group[0].Pepper {
				continue
			}
			compared++
			assert.NotEqual(t, group[0].Expected, group[i].Expected,
				"key %q hashes the same under two different peppers; the pepper is not the HMAC key", key)
		}
	}
	require.GreaterOrEqual(t, compared, 1,
		"no vector pair shares a key across two peppers, so pepper-sensitivity is untested")
}

// A short pepper must fail loudly. Degrading to an unpeppered digest would
// address a different Redis namespace and make every account look unmetered.
func TestHashAPIKey_RefusesAPepperThatIsTooShort(t *testing.T) {
	for _, pepper := range []string{"", "short", string(make([]byte, MinPepperLength-1))} {
		_, err := HashAPIKey(pepper, "vk_anything")
		require.Error(t, err, "a %d-character pepper must be refused, not used", len(pepper))
		assert.Contains(t, err.Error(), "at least")
	}

	_, err := HashAPIKey(string(make([]byte, MinPepperLength)), "vk_anything")
	assert.NoError(t, err, "a pepper of exactly the minimum length is valid; the boundary must not be off by one")
}
